name: Selenium (Browser Tests)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & npm exec -c "npm exec wdio"


    # TODO: change to heroku selenium tests, see if they pass
    # might need to load LAMP stack via a Docker container:
    # https://jasonmccreary.me/articles/install-apache-php-mysql-macos-docker-local-development/
    # https://www.google.com/search?q=github+actions+spin+up+apache+php+and+mysql+and+run+a+localhost
    # idea: put all my bash commands in Docker so I can more easily test GitHub Actions. then just use a one liner here that loads the Dockerfile
    # eventually, turn this into a GitHub Action called "LAMP stack + WebDriverIO". Good self marketing for RedDragonWebDesign. And I can include it in a bunch of my projects. Could be really useful to people. I feel like there's a huge gap in GitHub Actions for Selenium.
    # intermediate step: write a dockerfile that gets a localhost running on my computer for BlueThrust dev work. that'll be the exact same setup procedure for the selenium tests :)
